### ISSUE TITLE
Cannot run a given collector once and exit

### ISSUE THREAD

**Issue by hrchu** [python-diamond/Diamond#355] opened 2015-12-21 07:05 UTC
Hi, 
I follow the instruction [here](http://diamond.readthedocs.org/en/latest/Getting-Started/Custom-Collectors/)

When I fire diamond -f -l -r full/path/to/ExampleCollector.py, ExampleCollector does not executed. Anything do I missed?

**Comment by bigunyak** [comment] 2016-06-03 12:04
Yeah, this certainly doesn't work, diamond always loads all collectors from the `collectors_path`. The `--run` option is basically ignored.

**Comment by josegonzalez** [comment] 2016-11-25 04:49
Duplicate of #155

**Closed by josegonzalez** 2016-11-25 04:49 UTC
Labels: category:  collector, type: bug
