### ISSUE TITLE
Failure with influxdbHandler

### ISSUE THREAD

**Issue by flyingfish007** [python-diamond/Diamond#440] opened 2016-03-22 07:45 UTC
InfluxDB shell 0.10.3

[2016-03-22 15:43:19,929] [MainThread] Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/diamond/handler/Handler.py", line 72, in _process
    self.process(metric)
  File "/usr/lib/pymodules/python2.7/diamond/handler/influxdbHandler.py", line 151, in process
    self._send()
  File "/usr/lib/pymodules/python2.7/diamond/handler/influxdbHandler.py", line 182, in _send
    time_precision=self.time_precision)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 391, in write_points
    tags=tags)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 436, in _write_points
    expected_response_code=204
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 276, in write
    data=make_lines(data, precision).encode('utf-8'),
  File "/usr/local/lib/python2.7/dist-packages/influxdb/line_protocol.py", line 117, in make_lines
    for field_key in sorted(point['fields'].keys()):
KeyError: u'fields'

**Comment by josegonzalez** [comment] 2016-11-25 04:47
Our influxdb handler doesn't appear to support newer versions of influxdb.

**Comment by shortdudey123** [comment] 2017-02-19 09:12
Dupe of https://github.com/python-diamond/Diamond/issues/137

**Closed by shortdudey123** 2017-02-19 09:12 UTC
Labels: category: collector, type: enhancement
