### ISSUE TITLE
New Install Ubuntu 14.04 Issues with SNMPRawCollector & SNMPInterfaceCollector

### ISSUE THREAD

**Issue by jrpaz** [python-diamond/Diamond#309] opened 2015-10-17 13:50 UTC
I am seeing this issue with SNMPRawCollector & SNMPInterfaceCollector.

I am running on Ubuntu 14.04 LTS and followed the Wiki instalation procedures. 
Pysnmp is installed with the requried dependencies. 

CPUCollector,DiskSpaceCollector,DiskUsageCollector,LoadAverageCollector,MemoryCollector,VMStatCollector & NetworkCollector are working without issue so I am thinking it's something Pysnmp or something else that I can't think of

Here is my current SNMPInterfaceCollector config and exerpt from the diamond.log below

   Options for SNMPInterfaceCollector
    enabled = True
    byte_unit = bit
    path = interface
    interval = 60

```
 [devices]

[[sw01]]
host = superswitch.mega.co
port = 161
community = public
```
# diamond.log

[2015-10-17 08:15:03,223] [MainThread] Collector failed!
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/diamond/utils/scheduler.py", line 73, in collector_process
    collector._run()
  File "/usr/lib/pymodules/python2.7/diamond/collector.py", line 472, in _run
    self.collect()
  File "/usr/lib/pymodules/python2.7/diamond/collector.py", line 366, in collect
    raise NotImplementedError()
NotImplementedError

Any clues or guidance would be appreciated. Could it be a  simple config issue ?

**Comment by bmfurtado** [comment] 2015-10-22 18:11
Seems like the same reported on #219

**Comment by jrpaz** [comment] 2015-10-22 18:15
It is I think we should merge them

**Comment by josegonzalez** [comment] 2016-11-25 03:49
Duplicate of #219.

**Closed by josegonzalez** 2016-11-25 03:49 UTC
