### ISSUE TITLE
handler config in root config file does not work in 4.0

### ISSUE THREAD

**Issue by hvnsweeting** [python-diamond/Diamond#51] opened 2015-01-04 03:23 UTC
I upgraded my diamond to 4.0 but the config for handler in /etc/diamond/diamond.conf didn't work anymore. It used to work with 3.x.

Even I created /etc/diamond/handlers/ArchiveHandler.conf, diamond does not use it:

```
# cat /etc/diamond/handlers/ArchiveHandler.conf
[ArchiveHandler]
log_file = /var/cache/salt/minion/diamond.archive.log

```

log

```
Jan  4 10:21:01 integration-ubuntu diamond[30607] ERROR diamond diamond.main:299 Unhandled exception: [Errno 21] Is a directory: '/'

```

because it use the default path "", which turned to "/" by logging module code:

```
In [5]: os.path.abspath('')
Out[5]: '/'
```

Could you please provide a working example for handler config. Thanks

**Comment by pythianliappis** [comment] 2015-01-04 16:07
+1. I am getting the same issue and also looking for a valid diamond.conf; in 4.0 also the handlers definition in diamond.conf seems to be expected to be a string (enclosed in " ") otherwise it gets parsed as a list and fails when the split method is used.

**Comment by hvnsweeting** [comment] 2015-01-04 16:44
@pythianliappis  !47 may fix your problem

**Comment by kormoc** [comment] 2015-01-04 18:47
Can you try the current master and see if it fixes the issue?

**Comment by pythianliappis** [comment] 2015-01-04 19:14
@hvnsweeting Thanks a lot for the recommendation! Yes #47 fixes the issue with the string vs list definition of handlers.

However I am still experiencing the issue of log_file defined in the [[ArchiveHandler]] section, not honoured. I will try the last master as mentioned by kormoc kai see if this helps.

**Comment by pythianliappis** [comment] 2015-01-04 19:27
@kormoc I confirm that the last latest commit id: fc59d153379a0fde774fb59077b947a8740cd862 on master has fixed both issues; now diamond is running and has correctly processed the path in /etc/diamond/diamond.conf for the ArchiveHandler.

I successfully tested it both in centos65 and ubuntu trusty 64.

Thanks!

**Comment by chriscowley** [comment] 2015-01-05 19:44
It seems to me that (at least in my case) it is not descending into my collectors directory. More precisely, I have a file `cat /etc/diamond/collectors/DiskSpace.conf` which contains:

```
enabled = True
filesystems = ext2,ext3,ext4,xfs,btrfs
```

And Diamond is still sending info about my NFS mounts to Graphite.

**Comment by hvnsweeting** [comment] 2015-01-15 03:41
this problem is fixed in latest diamond (I'm using pip version 4.0.41). Anw, with the old config file, now diamond started with 17 processes, is that what new threading model suppose to do?

````
$ ps -ef | grep diamon[d] -c
17

root     22948     1  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
root     22955 22948  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
root     22967 22948  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
root     23008 22948  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
root     23035 22948  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
root     23100 22948  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
root     23141 22948  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
root     23170 22948  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
root     23211 22948  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
root     23238 22948  0 10:38 ?        00:00:00 /usr/local/diamond/bin/python /usr/local/diamond/bin/diamond --foreground
````

**Comment by beeftornado** [comment] 2015-03-02 22:48
Also confirmed this issue is present in latest release, but not in master. Thanks

**Comment by josegonzalez** [comment] 2016-11-25 03:23
Closing since it's fixed. I'm working on getting a release out now.

**Closed by josegonzalez** 2016-11-25 03:23 UTC
