### ISSUE TITLE
InfluxdbHandler raise InfluxDBClientError: 404: 404 page not found

### ISSUE THREAD

**Issue by huoxy** [python-diamond/Diamond#197] opened 2015-06-04 07:57 UTC
I found this import is the reason:

```
try:
    from influxdb.client import InfluxDBClient
except ImportError:
    InfluxDBClient = None
```

In fact, when influxdb -v == 0.8.x, the correct import should be:

```
from influxdb.influxdb08 import InfluxDBClient
```

ref: https://github.com/influxdb/influxdb-python/issues/135

**Comment by huoxy** [comment] 2015-06-04 07:58
ref: https://github.com/influxdb/influxdb-python/issues/135

**Comment by shortdudey123** [comment] 2017-02-19 09:12
Dupe of https://github.com/python-diamond/Diamond/issues/137

**Closed by shortdudey123** 2017-02-19 09:12 UTC
Labels: type: bug
