### ISSUE TITLE
New version won't start, stuck on "Starting process Handlers"

### ISSUE THREAD

**Issue by ghost** [python-diamond/Diamond#178] opened 2015-05-07 15:02 UTC
Hi,
I just attempted to upgrade Diamond from version 3.5.0. I first got the latest version in pip, then I tried directly installing from here.
I am pretty certain that the conf file is fine.
Every time I try to manually start a custom collector I get this in the log:

[root@target01 handlers]# /opt/comp/python/python-2.7.7/bin/diamond -l -f -r /usr/share/diamond/collectors/CoreRevFromPrevDay.py
1431010824.28   [MainProcess:2708:INFO] Changed UID: 0 () GID: 0 ().
1430953200
1431010824.41   [MainProcess:2708:DEBUG]        Loading Handler diamond.handler.graphite.GraphiteHandler
1431010829.45   [MainProcess:2708:DEBUG]        GraphiteHandler: Established connection to graphite server metrics.int-review.skyscanner.local:2003.
1431010829.45   [Handlers:2716:DEBUG]   Starting process Handlers

It does the same thing for starting the service too.

Has anyone got any clue what this might be?

I'm using CentOS 6.5

Thanks
Sybsw

**Comment by Sybsw** [comment] 2015-05-07 15:54
I tried to manually specify the conf file and got this:

[root@target01 diamond]# /opt/comp/python/python-2.7.7/bin/diamond -l -f -r /usr/share/diamond/collectors/CoreRevFromPrevDay.py -c /usr/share/diamond/collectors/CoreRevFromPrevDay.conf
1431014000.2    [MainProcess:2868:ERROR]        Unhandled exception: 'server'
1431014000.2    [MainProcess:2868:ERROR]        /opt/skyscanner/python/python-2.7.7/bin/diamond:299
1431014000.2    [MainProcess:2868:ERROR]        traceback: Traceback (most recent call last):
  File "/opt/skyscanner/python/python-2.7.7/bin/diamond", line 144, in main
    options.pidfile = str(config['server']['pid_file'])
  File "/opt/skyscanner/python/python-2.7.7/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'server'

1431014000.2    [MainProcess:2868:ERROR]        /opt/skyscanner/python/python-2.7.7/bin/diamond:300

**Comment by neilfordyce** [comment] 2015-05-11 09:57
Part of the issue is related to https://github.com/python-diamond/Diamond/issues/155

The -r option can't be used to specify a single collector in v4.0, so Diamond will be trying to run all of the collectors in collectors_path.

**Comment by Sybsw** [comment] 2015-05-11 11:42
Yep, that looks like what's causing part of it. The -r option for starting one collector has been broken.
However, I still can't get the service to start up either. It still stops writing to the log at the same point.

**Comment by josegonzalez** [comment] 2016-11-25 03:41
Duplicate of #155.

**Closed by josegonzalez** 2016-11-25 03:41 UTC
Labels: bug
