### ISSUE TITLE
MongoDBCollector sends spaces in metrics name

### ISSUE THREAD

**Issue by AlexAkulov** [python-diamond/Diamond#566] opened 2016-12-21 15:51 UTC
Hello! 
MongoDBCollector sends spaces in metrics name
```
MongoDB.spamSet.spam-mongo1.mongo.wiredTiger.log.consolidated slot join races 2269428 1482338184
MongoDB.spamSet.spam-mongo1.mongo.wiredTiger.log.pre-allocated log files used 205 1482338184
MongoDB.spamSet.spam-mongo1.mongo.wiredTiger.log.pre-allocated log files not ready and missed 16 1482338184
MongoDB.spamSet.spam-mongo1.mongo.wiredTiger.log.pre-allocated log files prepared 222 1482338184
MongoDB.spamSet.spam-mongo1.mongo.wiredTiger.log.consolidated slot unbuffered writes 2 1482338184
MongoDB.spamSet.spam-mongo1.mongo.wiredTiger.log.written slots coalesced 0 1482338184
MongoDB.spamSet.spam-mongo1.mongo.wiredTiger.log.number of pre-allocated log files to create 17 1482338184
```

**Comment by shortdudey123** [comment] 2016-12-21 17:07
Dupe of https://github.com/python-diamond/Diamond/issues/547

**Comment by shortdudey123** [comment] 2016-12-21 17:08
Please verify you are using a newer version (`v4.0.501` or newer so that you have https://github.com/python-diamond/Diamond/commit/57c0b86d0d4adac30111c41b2d35d16adb7901f0)

**Closed** 2016-12-22 09:14 UTC
