### ISSUE TITLE
Current release "has problems".

### ISSUE THREAD

**Issue by linsomniac** [python-diamond/Diamond#297] opened 2015-10-12 12:37 UTC
I had heard good things about Diamond, and I'm not that happy with collectd, so I thought I'd give it a look.

First problem, there are absolutely no docs.  No problem I thought, I'll write a GettingStarted and submit a pullreq for it.  Except that I could never get started myself.

I notice there is a "debian" subdirectory, so I try a debuild, and find that the 4.0 release produces a debian file named "3.1.0".  Submitted a PR.

Then I start up Diamond after copying the example config over to diamond.conf and I'm getting a Traceback that the handlers list object has no split(',') method.  Ooook, so that's supposed to be a string instead?  I quote it in the config file, but then I'm running into more problems.

I finally decide to grab the latest code and see if that worked without quotes on the handlers line.  It does and at least I have it writing to the archive handler.

Buuut...  The Influxdb handler doesn't seem to be doing anything.  No logs I can see to say why, just silently isn't doing anything.

Recommendations:

You probably at least need to tag a new release, fix the debian/changelog file, and put out _some_ sort of docs.

**Comment by jaingaurav** [comment] 2015-10-12 14:24
Thanks for your comments and for your comments and for attempting to help with some of the issues. Regarding the release packaging process, we currently recommend that people use pip and specify HEAD or a commit version as necessary. This results in a version number that reflects the commit that was used. The rpm/Debian packaging needs some love to get up to par, so we would greatly appreciate the help. Currently your PR doesn't quite do the right thing as it is hard coded to 4.0.0 as opposed to making the last number the commit number.

Regarding documentation, there is documentation via the github wiki. Some of this is a bit stale and needs some help. I think your Getting Started guide would be very welcome.

Could you post how you are running diamond? Based on the configuration you have, the output logs might be going to a log file instead of stdout

**Comment by linsomniac** [comment] 2015-10-12 21:25
Thanks for the pointers, I totally missed the link to the Wiki in the README.  I've made a PR that adds a specific Getting Started section to make these things more clear.  I also in that mention that the Releases is not the preferred way to grab stable code.

I've built up a package using that tagging via "pypi-install" to make Debian packages.

The issue I'm having with the InfluxdbHandler is with line 182 of influxdbHandler.py, where it calls self.influx.write_points, it then goes into the influxdb/line_protocol.py" library on line 118 where it is trying to access "point['fields']", but has no key "fields".  The "point" dictionary is:

{'points': [[1444670801, 0]], 'name': 'servers.graph.iostat.vda1.writes_byte', 'columns': ['time', 'value']}

I'm wondering if "columns" should instead be "fields"?

The full traceback is:

    [2015-10-12 11:26:40,777] [MainThread] InfluxdbHandler: Error sending metrics, waiting for 4s.
    [2015-10-12 11:26:40,783] [MainThread] Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/diamond/handler/Handler.py", line 72, in _process
        self.process(metric)
      File "/usr/lib/python2.7/dist-packages/diamond/handler/influxdbHandler.py", line 151, in process
        self._send()
      File "/usr/lib/python2.7/dist-packages/diamond/handler/influxdbHandler.py", line 182, in _send
        time_precision=self.time_precision)
      File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 387, in write_points
        tags=tags)
      File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 432, in _write_points
        expected_response_code=204
      File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 275, in write
        data=make_lines(data, precision).encode('utf-8'),
      File "/usr/lib/python2.7/dist-packages/influxdb/line_protocol.py", line 118, in make_lines
        for field_key in sorted(point['fields'].keys()):
    KeyError: u'fields'

The python-influxdb package is version 2.9.2

The docstring in influxdbHandler says it needs to be version 0.1.6 or newer for https support, so I wonder if the influxdbHandler is just waaaaay out of date?

**Comment by jrpaz** [comment] 2015-10-17 13:44
Does this affect usered who followed the wiki for installation on Ubuntu setups?

**Comment by musskopf** [comment] 2015-10-23 03:19
Same issue over here. Installed it on RHEL 6 and a fresh Python 2.7 using:

pip install diamond

Here the versions from pip list:
diamond (4.0.195)
influxdb (2.9.2)

But apparently is because I'm running influxDB 0.9. There are some comments about that here:

https://github.com/python-diamond/Diamond/issues/217

**Comment by linsomniac** [comment] 2015-10-23 15:45
FYI: I was running InfluxDB 0.9 as well.

**Comment by bluecamel** [comment] 2015-10-24 21:18
I also have this on Ubuntu 14.04, following the wiki for installing on Ubuntu.  Also InfluxDB 0.9.

**Comment by bluecamel** [comment] 2015-10-24 23:52
Okay, the problem is that the handler is written to use a very old version of influxdb-python (I believe for influxdb 0.8).  I've "fixed" it locally by converting the batch to the correct format for the client, but I'm not familiar enough with influxdb to know how I should convert the path into a metric name and tags.  I played with it a bit, but I'm truly a noob with both influxdb and grafana (I'm used to graphite) and really not sure how things should be done in this world.  I ended up just sending no tags and just the path as the measurement name.

I'm not sure how useful my fix would be for others, as I'm still learning, but I'd be happy to do a PR.  It seems that the collector or handler should maybe be passing tags and measurement name instead of path, or maybe it's up to the influxdb handler to convert the path.  Not sure.

If anyone can tell me how something like "servers.wooha.diskspace.root.byte_percentfree" should be converted to measurement name and tags, I'd be happy to include that and submit a PR.

In the meantime, I'll try to learn a bit more about influxdb and grafana ;)

**Comment by bluecamel** [comment] 2015-10-25 06:06
I went ahead and submitted a pull request: https://github.com/python-diamond/Diamond/pull/312

**Comment by musskopf** [comment] 2015-10-25 21:28
This one seems to be working:
https://github.com/Clever/Diamond/blob/726e8cc8b4cf8d6de77d463155cab87bf1f4ffee/src/diamond/handler/influxdbHandler.py

As a quick fix just download it and replace the current one. Don't forget to update the handle config to include version. Hopefully it'll be merged back to be part of the next release.

Cheers!

**Comment by bluecamel** [comment] 2015-10-26 01:10
musskopf, that works for you with InfluxDB 0.9?  Doesn't work for me since it's still trying to send in the wrong format.

**Comment by musskopf** [comment] 2015-10-26 01:13
Yes, it works... have you updated your handles configuration? If the version is not defined it'll default to 0.8. The configuration example is on the comment at the top of the file.

**Comment by bluecamel** [comment] 2015-10-27 00:20
Oh, I see now.  That repo has another handler that does very similar to my PR: https://github.com/Clever/Diamond/blob/726e8cc8b4cf8d6de77d463155cab87bf1f4ffee/src/diamond/handler/influxdb9Handler.py

Is python-diamond not accepting PRs and so folks are just maintaining forks?

**Comment by astlock** [comment] 2015-11-15 11:26
The same problem on CentOS6.5, diamond-3.5.8, influxdb-2.10.0. Python-2.6.6, InfluxDB-0.9.4.2.
```
[2015-11-15 11:24:18,172] [Thread-38] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/handler/Handler.py", line 69, in _process
    self.process(metric)
  File "/usr/lib/python2.6/site-packages/diamond/handler/influxdbHandler.py", line 154, in process
    self._send()
  File "/usr/lib/python2.6/site-packages/diamond/handler/influxdbHandler.py", line 185, in _send
    time_precision=self.time_precision)
  File "/usr/lib/python2.6/site-packages/influxdb/client.py", line 373, in write_points
    tags=tags)
  File "/usr/lib/python2.6/site-packages/influxdb/client.py", line 418, in _write_points
    expected_response_code=204
  File "/usr/lib/python2.6/site-packages/influxdb/client.py", line 258, in write
    data=make_lines(data, precision).encode('utf-8'),
  File "/usr/lib/python2.6/site-packages/influxdb/line_protocol.py", line 117, in make_lines
    for field_key in sorted(point['fields'].keys()):
KeyError: u'fields'
```

**Comment by jaingaurav** [comment] 2015-11-15 18:11
@bluecamel Just commented on your PR. With your changes we can hopefully merge it in.

Sorry, about the slow response to PRs. Seems a lot of the maintainers are quite tied up these days. Feel free to poke us either on github or IRC if you're not getting a response fast enough.

**Comment by shortdudey123** [comment] 2022-05-25 00:15
Final issue in this is influxdb.  See #137.

**Closed by shortdudey123** 2022-05-25 00:15 UTC
Labels: type: bug, category: collector, status: fix-provided, handler: influxdb
