### ISSUE TITLE
upgrade InfluxDB handler to support 0.9x - Request for comment

### ISSUE THREAD

**Issue by prune998** [python-diamond/Diamond#278] opened 2015-09-21 19:00 UTC
Hi,

InfluxDB reached 0.9.x release with a massive API and organization change. 
It's time to re-write the handler.

Previously, influx was storing metrics like graphite, describing the content using chunks. ex :  servers.myhost.cpu.user.time = 0.2

When searching, a regexp was used to split every parts. This wasn't really effective in influxdb.

InfluxDB 0.9 is using tags to give informations on the metrics. The same example as above could be change to :  
cpu_time: value=0.2 host=myhost type=user

To be able to do that using Diamond, each collector must create its own tags. This could be a massive rewrite !

The name also have to be changed to something that describe the same kind of metric.
Still using the example above, for CPU, I could have many CPUs in the system. The collector will have to tag every metric with the number (or the name) of the CPU, in the same serie name for each metric :

cpu_time: value=0.2 host=myhost type=user cpu=0
cpu_time: value=0.5 host=myhost type=user cpu=1
cpu_time: value=0.2 host=myhost type=nice cpu=0
cpu_time: value=0.5 host=myhost type=nice cpu=1
...

This way, we can easily search for the whole cpu_time (select value from cpu_time), for one specific server (select value from cpu_time where host=myhost) or from one type of cpu usage (select value from cpu_time where host=myhost and type=nice)

This is a big change.

I would like to have your thoughts on this, and maybe a new/better idea to solve this issue and enable the use of influxdb 0.9 with Diamond.

**Comment by mattrobenolt** [comment] 2015-09-21 19:10
fwiw, this concept is similarly needed to support datadog better as well.

**Comment by prune998** [comment] 2015-09-22 12:29
I'm reading some collector's code right now. 
The base PATH (which is generated by diamond itself) is easy to cut in to chunks.
The next key is the collector (ex : cpu, elasticsearch).
All this could happen in the Influxdb Handler, without touching anything.

For the detailed metrics, then, I see two options : 
- change every collector to send a dict associated with the metric when calling the self.publish() def
- maintain a reversed key/value description file along with the collector that will be looked-up by the Influxdb handler

2nd solution is less invasive but is a pain to maintain. Also, in the event where a metric is not in the lookup list, everything will be split into key1=<>, key2=<> which may be another pain to use later... Finaly, having so many lookups may have performance issues...

I would really like to have a feedback from Diamond devs.

FYI, it seems the collectd input in Influxdb use the "dot separated values" as <key1>.<value1>.<key2>.<val2> and so on... Which does not seem to be a good solution to me.

**Comment by prune998** [comment] 2015-10-19 12:51
It's sad almost no-one have interrest for that. 
My thinking is that i'm going to switch from Diamond to Telegraf, the tool from Influxdb guys, and use Kafka as a queue.

**Comment by jaingaurav** [comment] 2015-10-19 15:30
@prune998: I don't think there is a lack of interest, just resources. If you are able to dedicate some time to work on this, I'm sure we'd welcome such a change

**Comment by prune998** [comment] 2015-10-19 15:38
@jaingaurav it's a BIG change in how Diamond work, and I won't be able to do it on my own. To do it correctly, Diamond will require some massive rewrite that may involve other handlers too.
I see this as a good improvement, and it may benefit other handlers like Datadog (not only Influxdb). But it have a cost...

**Comment by shortdudey123** [comment] 2017-02-19 09:13
Dupe of https://github.com/python-diamond/Diamond/issues/137

**Closed by shortdudey123** 2017-02-19 09:13 UTC
Labels: category: collector, type: enhancement
